"""add versioned tool registry

Revision ID: 928edc5afeb0
Revises: b48f1c2d9a70
Create Date: 2026-07-14 00:11:20.451604

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "928edc5afeb0"
down_revision: str | Sequence[str] | None = "b48f1c2d9a70"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tool_definitions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("tool_key", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "tool_key ~ '^[a-z][a-z0-9._-]{0,99}$'", name=op.f("ck_tool_definitions_tool_key_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_definitions")),
        sa.UniqueConstraint("team_id", "id", name="team_tool_identity"),
        sa.UniqueConstraint("team_id", "tool_key", name="team_tool_key"),
    )
    op.create_table(
        "tool_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tool_definition_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'", name=op.f("ck_tool_versions_content_hash_valid")
        ),
        sa.CheckConstraint(
            "jsonb_typeof(manifest) = 'object'", name=op.f("ck_tool_versions_manifest_is_object")
        ),
        sa.CheckConstraint(
            "version_number > 0", name=op.f("ck_tool_versions_version_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["tool_definition_id"],
            ["tool_definitions.id"],
            name=op.f("fk_tool_versions_tool_definition_id_tool_definitions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_versions")),
        sa.UniqueConstraint("tool_definition_id", "id", name="tool_definition_version_identity"),
        sa.UniqueConstraint("tool_definition_id", "version_number", name="tool_definition_version"),
    )
    op.create_index(
        "ix_tool_versions_definition_created",
        "tool_versions",
        ["tool_definition_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "agent_tool_bindings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_version_id", sa.Uuid(), nullable=False),
        sa.Column("tool_definition_id", sa.Uuid(), nullable=False),
        sa.Column("tool_version_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_version_id"],
            ["agent_versions.id"],
            name=op.f("fk_agent_tool_bindings_agent_version_id_agent_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tool_definition_id", "tool_version_id"],
            ["tool_versions.tool_definition_id", "tool_versions.id"],
            name="agent_binding_tool_version",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_tool_bindings")),
        sa.UniqueConstraint("agent_version_id", "tool_definition_id", name="agent_stable_tool"),
    )
    op.create_index(
        "ix_agent_tool_bindings_agent_version",
        "agent_tool_bindings",
        ["agent_version_id", "tool_version_id"],
        unique=False,
    )
    op.create_table(
        "tool_conformance_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tool_version_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('passed', 'failed')", name=op.f("ck_tool_conformance_runs_status_valid")
        ),
        sa.CheckConstraint(
            "completed_at >= started_at",
            name=op.f("ck_tool_conformance_runs_completed_at_not_before_started_at"),
        ),
        sa.ForeignKeyConstraint(
            ["tool_version_id"],
            ["tool_versions.id"],
            name=op.f("fk_tool_conformance_runs_tool_version_id_tool_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_conformance_runs")),
        sa.UniqueConstraint("tool_version_id", "id", name="tool_version_conformance_identity"),
    )
    op.create_index(
        "ix_tool_conformance_runs_version_completed",
        "tool_conformance_runs",
        ["tool_version_id", "completed_at"],
        unique=False,
    )
    op.create_table(
        "tool_conformance_case_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("case_key", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("diagnostic_code", sa.String(length=200), nullable=True),
        sa.CheckConstraint(
            """
            (status = 'passed' AND diagnostic_code IS NULL)
            OR
            (
                status = 'failed'
                AND diagnostic_code ~ '^[a-z][a-z0-9._-]{0,199}$'
            )
            """,
            name=op.f("ck_tool_conformance_case_results_diagnostic_matches_status"),
        ),
        sa.CheckConstraint(
            "case_key ~ '^[a-z][a-z0-9._-]{0,99}$'",
            name=op.f("ck_tool_conformance_case_results_case_key_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('passed', 'failed')",
            name=op.f("ck_tool_conformance_case_results_status_valid"),
        ),
        sa.CheckConstraint(
            "duration_ms BETWEEN 0 AND 300000",
            name=op.f("ck_tool_conformance_case_results_duration_ms_bounded"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["tool_conformance_runs.id"],
            name=op.f("fk_tool_conformance_case_results_run_id_tool_conformance_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_conformance_case_results")),
        sa.UniqueConstraint("run_id", "case_key", name="conformance_run_case"),
    )
    op.create_table(
        "tool_version_states",
        sa.Column("tool_version_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("activated_conformance_run_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            """
            (status = 'draft' AND activated_conformance_run_id IS NULL)
            OR status = 'disabled'
            OR (
                status IN ('active', 'deprecated')
                AND activated_conformance_run_id IS NOT NULL
            )
            """,
            name=op.f("ck_tool_version_states_activation_matches_status"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'active', 'deprecated', 'disabled')",
            name=op.f("ck_tool_version_states_status_valid"),
        ),
        sa.CheckConstraint("revision > 0", name=op.f("ck_tool_version_states_revision_positive")),
        sa.CheckConstraint(
            "updated_at >= created_at",
            name=op.f("ck_tool_version_states_updated_at_not_before_created_at"),
        ),
        sa.ForeignKeyConstraint(
            ["tool_version_id", "activated_conformance_run_id"],
            ["tool_conformance_runs.tool_version_id", "tool_conformance_runs.id"],
            name="tool_version_state_activation_run",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tool_version_id"],
            ["tool_versions.id"],
            name="tool_version_state_version",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("tool_version_id", name=op.f("pk_tool_version_states")),
    )
    op.create_index(
        "ix_tool_version_states_eligible",
        "tool_version_states",
        ["status", "tool_version_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tool_version_states_eligible", table_name="tool_version_states")
    op.drop_table("tool_version_states")
    op.drop_table("tool_conformance_case_results")
    op.drop_index("ix_tool_conformance_runs_version_completed", table_name="tool_conformance_runs")
    op.drop_table("tool_conformance_runs")
    op.drop_index("ix_agent_tool_bindings_agent_version", table_name="agent_tool_bindings")
    op.drop_table("agent_tool_bindings")
    op.drop_index("ix_tool_versions_definition_created", table_name="tool_versions")
    op.drop_table("tool_versions")
    op.drop_table("tool_definitions")
    # ### end Alembic commands ###
