"""add execution events

Revision ID: adfa099fa157
Revises: ce2efcfed3d1
Create Date: 2026-07-13 17:16:02.971478

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "adfa099fa157"
down_revision: str | Sequence[str] | None = "ce2efcfed3d1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("turn_attempt_identity", "turn_attempts", ["turn_id", "id"])
    op.create_table(
        "execution_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("turn_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_id", sa.Uuid(), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            """
            kind IN (
                'turn.started',
                'response.delta',
                'turn.completed',
                'turn.failed'
            )
            """,
            name=op.f("ck_execution_events_kind_valid"),
        ),
        sa.CheckConstraint(
            "jsonb_typeof(payload) = 'object'", name=op.f("ck_execution_events_payload_is_object")
        ),
        sa.CheckConstraint("sequence > 0", name=op.f("ck_execution_events_sequence_positive")),
        sa.ForeignKeyConstraint(
            ["turn_id", "attempt_id"],
            ["turn_attempts.turn_id", "turn_attempts.id"],
            name="execution_event_attempt",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["turn_id"],
            ["turns.id"],
            name=op.f("fk_execution_events_turn_id_turns"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_execution_events")),
        sa.UniqueConstraint("turn_id", "sequence", name="turn_event_sequence"),
    )
    op.create_index(
        "uq_execution_events_one_terminal_per_turn",
        "execution_events",
        ["turn_id"],
        unique=True,
        postgresql_where=sa.text("kind IN ('turn.completed', 'turn.failed')"),
    )
    op.add_column(
        "turns",
        sa.Column("next_event_sequence", sa.Integer(), server_default=sa.text("1"), nullable=False),
    )
    op.alter_column("turns", "next_event_sequence", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("turns", "next_event_sequence")
    op.drop_index(
        "uq_execution_events_one_terminal_per_turn",
        table_name="execution_events",
        postgresql_where=sa.text("kind IN ('turn.completed', 'turn.failed')"),
    )
    op.drop_table("execution_events")
    op.drop_constraint("turn_attempt_identity", "turn_attempts", type_="unique")
    # ### end Alembic commands ###
