"""create conversation model

Revision ID: ce2efcfed3d1
Revises:
Create Date: 2026-07-13 11:03:58.790511

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce2efcfed3d1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_definitions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("btrim(name) <> ''", name=op.f("ck_agent_definitions_name_not_blank")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_definitions")),
    )
    op.create_index("ix_agent_definitions_team_id", "agent_definitions", ["team_id"], unique=False)
    op.create_table(
        "agent_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_definition_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "version_number > 0", name=op.f("ck_agent_versions_version_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["agent_definition_id"],
            ["agent_definitions.id"],
            name=op.f("fk_agent_versions_agent_definition_id_agent_definitions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_versions")),
        sa.UniqueConstraint(
            "agent_definition_id", "version_number", name="agent_definition_version"
        ),
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("default_agent_version_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("next_message_sequence", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('active', 'closed')", name=op.f("ck_conversations_status_valid")
        ),
        sa.CheckConstraint(
            "next_message_sequence > 0",
            name=op.f("ck_conversations_next_message_sequence_positive"),
        ),
        sa.CheckConstraint(
            "updated_at >= created_at",
            name=op.f("ck_conversations_updated_at_not_before_created_at"),
        ),
        sa.ForeignKeyConstraint(
            ["default_agent_version_id"],
            ["agent_versions.id"],
            name=op.f("fk_conversations_default_agent_version_id_agent_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    op.create_index(
        "ix_conversations_team_status", "conversations", ["team_id", "status"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("btrim(content) <> ''", name=op.f("ck_messages_content_not_blank")),
        sa.CheckConstraint("role IN ('user', 'assistant')", name=op.f("ck_messages_role_valid")),
        sa.CheckConstraint("sequence > 0", name=op.f("ck_messages_sequence_positive")),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint("conversation_id", "id", name="conversation_message_identity"),
        sa.UniqueConstraint("conversation_id", "sequence", name="conversation_message_sequence"),
    )
    op.create_table(
        "turns",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("input_message_id", sa.Uuid(), nullable=False),
        sa.Column("agent_version_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            """
            (
                status IN ('received', 'running')
                AND completed_at IS NULL
            )
            OR
            (
                status IN ('completed', 'failed', 'cancelled')
                AND completed_at IS NOT NULL
            )
            """,
            name=op.f("ck_turns_completion_matches_status"),
        ),
        sa.CheckConstraint(
            "status IN ('received', 'running', 'completed', 'failed', 'cancelled')",
            name=op.f("ck_turns_status_valid"),
        ),
        sa.CheckConstraint(
            "completed_at IS NULL OR completed_at >= created_at",
            name=op.f("ck_turns_completed_at_not_before_created_at"),
        ),
        sa.ForeignKeyConstraint(
            ["agent_version_id"],
            ["agent_versions.id"],
            name=op.f("fk_turns_agent_version_id_agent_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id", "input_message_id"],
            ["messages.conversation_id", "messages.id"],
            name="turn_input_message",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_turns")),
        sa.UniqueConstraint("input_message_id", name="input_message_turn"),
    )
    op.create_index(
        "ix_turns_conversation_status", "turns", ["conversation_id", "status"], unique=False
    )
    op.create_table(
        "turn_attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("turn_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_code", sa.String(length=100), nullable=True),
        sa.CheckConstraint(
            """
            (
                status = 'pending'
                AND started_at IS NULL
                AND completed_at IS NULL
                AND failure_code IS NULL
            )
            OR
            (
                status = 'running'
                AND started_at IS NOT NULL
                AND completed_at IS NULL
                AND failure_code IS NULL
            )
            OR
            (
                status = 'succeeded'
                AND started_at IS NOT NULL
                AND completed_at IS NOT NULL
                AND failure_code IS NULL
            )
            OR
            (
                status = 'failed'
                AND started_at IS NOT NULL
                AND completed_at IS NOT NULL
                AND failure_code IS NOT NULL
                AND btrim(failure_code) <> ''
            )
            """,
            name=op.f("ck_turn_attempts_lifecycle_fields_match_status"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'running', 'succeeded', 'failed')",
            name=op.f("ck_turn_attempts_status_valid"),
        ),
        sa.CheckConstraint(
            "attempt_number > 0", name=op.f("ck_turn_attempts_attempt_number_positive")
        ),
        sa.CheckConstraint(
            "completed_at IS NULL OR (started_at IS NOT NULL AND completed_at >= started_at)",
            name=op.f("ck_turn_attempts_completed_at_not_before_started_at"),
        ),
        sa.CheckConstraint(
            "started_at IS NULL OR started_at >= created_at",
            name=op.f("ck_turn_attempts_started_at_not_before_created_at"),
        ),
        sa.ForeignKeyConstraint(
            ["turn_id"],
            ["turns.id"],
            name=op.f("fk_turn_attempts_turn_id_turns"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_turn_attempts")),
        sa.UniqueConstraint("turn_id", "attempt_number", name="turn_attempt_number"),
    )
    op.create_index(
        "ix_turn_attempts_turn_status", "turn_attempts", ["turn_id", "status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_turn_attempts_turn_status", table_name="turn_attempts")
    op.drop_table("turn_attempts")
    op.drop_index("ix_turns_conversation_status", table_name="turns")
    op.drop_table("turns")
    op.drop_table("messages")
    op.drop_index("ix_conversations_team_status", table_name="conversations")
    op.drop_table("conversations")
    op.drop_table("agent_versions")
    op.drop_index("ix_agent_definitions_team_id", table_name="agent_definitions")
    op.drop_table("agent_definitions")
    # ### end Alembic commands ###
